site_name: CassiaDB Docs
pages:
  - Home: index.md
  - API:
    - Read/Write:
      - Create.md
      - Read.md
      - LookupValue.md
      - ReadKeys.md
      - Update.md
      - Delete.md
    - Query:
      - Query.md
    - Utility:
      - Count.md
      - List.md
      - Ping.md
      - Result.md
      - GetTableID.md
      - GetTableKeys.md
      - GetTableNames.md
      - LoadTable.md
      - UnloadTable.md
      - GetTeamID.md
    - Sync:
      - SyncPartial.md
      - SyncEvery.md
      - SyncComplete.md
    - Export:
      - ExportAsJSON.md
      - ExportAsLSON.md
    - Batch:
      - BatchCreate.md
      - BatchUpdate.md
      - BatchDelete.md
      - BatchQuery.md
      - BatchRead.md
      - BatchReadKeys.md
      - BatchMerge.md
  - Other Info:
    - Livecache.md
    - Metadata.md
    - QueryOperators.md
theme: mkdocs
