site_name: LiveCloud Documentation
site_url: https://docs.livecloud.io
site_description: LiveCloud Documentation site
site_author: Canela Software
copyright: © 2018, Canela Software, Inc.
site_dir:  html
nav:
  - Home: 'index.md'
  - Tutorials:
    - Setting Up LiveCloud: 'Setup.md'
    - Simple CRUD Example: 'CRUDExample.md'
    - Building Standalones: 'Standalone.md'
    - Authorization and Accounts: 'AddingUsers.md'
  - CanelaDB in Detail:
    - CDBCache: 'CDBCache.md'
    - Metadata: 'metadata.md'
    - Query Operators: 'QueryOperators.md'
  - CanelaDB API Reference:
    - CRUD:
        - Create: 'Create.md'
        - BatchCreate: 'BatchCreate.md'        
        - Read: 'Read.md'
        - BatchRead: 'BatchRead.md'
        - ReadKeys: 'ReadKeys.md'
        - BatchReadKeys: 'BatchReadKeys.md'
        - LookupValue: 'LookupValue.md'
        - Update: 'Update.md'
        - BatchUpdate: 'BatchUpdate.md'
        - BatchMerge: 'BatchMerge.md'
        - Delete: 'Delete.md'
        - BatchDelete: 'BatchDelete.md'
        - DeleteKeys: 'DeleteKeys.md'
        - BatchDeleteKeys: 'BatchDeleteKeys.md'
    - Query:
        - Query: 'Query.md'
        - AdvancedQuery: 'AdvancedQuery.md'
        - BatchQuery: 'BatchQuery.md'
        - BatchAdvancedQuery: 'BatchAdvancedQuery.md'
    - Blob:
        - CreateBlob: 'CreateBlob.md'
        - BatchCreateBlob: 'BatchCreateBlob.md'
        - DeleteBlob: 'DeleteBlob.md'
        - BatchDeleteBlob: 'BatchDeleteBlob.md'
        - ReadBlob: 'ReadBlob.md'
        - BatchReadBlob: 'BatchReadBlob.md'
        - UpdateBlob: 'UpdateBlob.md'
        - BatchUpdateBlob: 'BatchUpdateBlob.md'
        - ClearTempBlobs: 'ClearTempBlobs.md'
    - Auth:
        - Auth: 'Auth.md'
        - AuthStatus: 'AuthStatus.md'
        - Logout: 'Logout.md'
        - LoggedInUser: 'LoggedInUser.md'
    - User Accounts:
        - CreateUserAccount: 'CreateUserAccount.md'
        - DeleteUserAccount: 'DeleteUserAccount.md'
        - ReadUserAccount: 'ReadUserAccount.md'
        - ReadUsersByEmail: 'ReadUsersByEmail.md'
        - ResendVerificationEmail: 'ResendVerificationEmail.md'
        - UpdateUserAccount: 'UpdateUserAccount.md'
        - UserTableName: 'UserTableName.md'
    - Utilities:
        - Count: 'Count.md'
        - BatchCount: 'BatchCount.md'
        - List: 'List.md'
        - Sort: 'Sort.md'
        - BatchSort: 'BatchSort.md'
        - SDK: 'SDK.md'
        - SdkBuild: 'SdkBuild.md'
        - SendEmail: 'SendEmail.md'
        - Sync: 'Sync.md'
        - TableID: 'TableID.md'
        - TeamID: 'TeamID.md'
        - ProjectID: 'ProjectID.md'
        - ProjectTableIDs: 'ProjectTableIDs.md'
        - LoadTable: 'LoadTable.md'
        - UnloadTable: 'UnloadTable.md'
    - Error Checking:
        - Result: 'Result.md'
        - SetLogMode: 'SetLogMode.md'
    - Internet:
        - CheckInternetStatus: 'CheckInternetStatus.md'
        - FlushCache: 'FlushCache.md'
        - Ping: 'Ping.md'
        - PingNode: 'PingNode.md'
        - SetCloudTolerance: 'SetCloudTolerance.md'
        - SetFlushCacheInterval: 'SetFlushCacheInterval.md'
        - SetUploadMethod: 'SetUploadMethod.md'
    - Export:
        - ExportAsJSON: 'ExportAsJSON.md'
        - ExportAsLSON: 'ExportAsLSON.md'
    - Table Management:
        - CreateTable: 'CreateTable.md'
        - RenameTable: 'RenameTable.md'
        - Schemaless: 'Schemaless.md'
        - UpdateTableSchemaMode: 'UpdateTableSchemaMode.md'
        - DeleteTable: 'DeleteTable.md'
        - AddKeys: 'AddKeys.md'
        - RenameKey: 'RenameKey.md'
        - RemoveKeys: 'RemoveKeys.md'
        - TableKeys: 'TableKeys.md'
        - TableKeysType: 'TableKeysType.md'
        - TableName: 'TableName.md'
        - TableNames: 'TableNames.md'
        - AddTableToProject: 'AddTableToProject.md'
        - RemoveTableFromProject: 'RemoveTableFromProject.md'
    - Project Management:
        - CreateProject: 'CreateProject.md'
        - RenameProject: 'RenameProject.md'
        - DeleteProject: 'DeleteProject.md'
        - ProjectDetail: 'ProjectDetail.md'
        - ProjectInfo: 'ProjectInfo.md'
        - ProjectName: 'ProjectName.md'
        - ProjectNames: 'ProjectNames.md'

  - Other Info:
    - LiveCloud Homepage: 'https://livecloud.io'
    - LiveCloud Forums: 'https://forums.livecloud.io'
markdown_extensions:
  - toc
theme:
    name: readthedocs
    titles_only: true
    navigation_depth: 3
    custom_dir: theme_customizations/
    hljs_style: a11y-dark
    hljs_languages:
      - livecodeserver
